# send to container based infrastructure: http://docs.travis-ci.com/user/workers/container-based-infrastructure/
sudo: false

cache:
  directories:
  - $HOME/.m2
  - node
  - node_modules
  - src/main/frontend/lib

language: java

deploy:
  provider: heroku
  api_key:
    secure: "vu+C8dVToxn/uV/7gGIyYVwy65TjNtOUx0eK9EkFBGJpMARj4YhwxxSnsIdsqL/IAi8WZXs/z23hg8eo0dPrt75PRO5FmjGvi7grnlI6j2ADVtwdJEoDG6DYsvnpJ5m62k8IQuP/Sh1T2Qp+vjlYPjPuXOPHQBhwyzzBZqgyoBw="
  app: talk-spinner
  on:
    repo: jkirsch/spring-boot-spinner