# Set the platform to h2
# which automatically imports data-h2.sql when no profile is set
spring:
    datasource:
        platform: h2
    cloud:
        config:
            enabled: false

---
spring:
    profiles: cloud
    datasource:
        platform: psql
    jpa:
        hibernate:
            ddl-auto: update