# Set the platform to h2
# which automatically imports data-h2.sql when no profile is set
spring:
    datasource:
        platform: h2
    cloud:
        config:
            enabled: false
    h2:
        console:
            enabled: true

server:
    compression:
      enabled: true
      mime-types: text/html,application/json,application/javascript,text/css,text/plain
      min-response-size: 256
---
spring:
    profiles: cloud
    datasource:
        platform: psql
    jpa:
        hibernate:
            ddl-auto: update

server:
    compression:
      enabled: true
      mime-types: text/html,application/json,text/css,text/plain
      min-response-size: 256
